### ISSUE TITLE
Missing virtual specifier in ModuleGeneration.h

### ISSUE THREAD

**Issue by juancaflorez** [DominikPeacock/ue4-new-module-tool#5]
The file ModuleGeneration.h is missing the _virtual_ specifier before the class methods StartupModule and ShutdownModule
```
/** IModuleInterface implementation */
virtual void StartupModule() override;
virtual void ShutdownModule() override;	
```

**Comment by DominikPeacock** [comment]
Thanks for the feedback. You're totally right. I looked at the coding standard and it actually has a section saying you should always write both: https://docs.unrealengine.com/en-US/ProductionPipelines/DevelopmentSetup/CodingStandard/index.html. I'll adjust this next update.

Background for this: I made it a habit to skip the virtual keyword and only write override at the end. 
I find adding virtual again is a bit redundant since override already implies the function is virtual. I'll be switching this to the code standard though (so with virtual added).

**Comment by DominikPeacock** [comment]
Fixed for real this time ;)
